version: 2.1

workflows:
  maven_test:
    jobs:
      # Seperating job step as multiple other jobs may depend on this
      - clean
      - unit_tests:
          requires:
            - clean
      - integration_test:
          requires:
            - unit_tests
      - deploy:
          requires:
            - integration_test
          
jobs:
  clean:
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the docker image tag below to openjdk version of your application.
    # A list of available CircleCI docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:11.0
    steps:
      # Checkout the code as the first step.
      - checkout
      # Use mvn clean as the standard maven build phase
      - run:
          name: Clean
          command: mvn -B -DskipTests clean
  unit_tests:
      docker:
        - image: cimg/openjdk:11.0
      steps:
        - checkout
        - run:
            name: Unit Tests
            command: mvn package
  integration_test:
      docker:
        - image: cimg/openjdk:11.0
      steps:
        - checkout
        - run:
            name: Integration Test
            command: mvn verify
        - store_artifacts:
            path:  target/site/jacoco
        - store_artifacts:
            path:  target/surefire-reports
  deploy:
      docker:
        - image: cimg/openjdk:11.0
      steps:
        - checkout
        - run:
            name: Test
            command: git merge pr/10
