version: 2.1

workflows:
  # Only 1 workflow needed. Runs jobs listed in this file
  maven_test:
    jobs:
      - clean
      - unit_tests:
          requires:
            - clean
      - integration_test:
          requires:
            - unit_tests
      - merge:
          requires:
            - integration_test

executors:
  # Specifying executor to run jobs
  doc:
    docker:
      - image: cimg/openjdk:11.0


jobs:
  # Job to clean project before testing
  clean:
    executor: doc
    steps:
      - checkout
      - run:
          name: Clean
          command: mvn clean
  # Job to run unit tests
  unit_tests:
      executor: doc
      steps:
        - checkout
        - run:
            name: Unit Tests
            command: mvn package
  # Job to run the integration test
  integration_test:
      executor: doc
      steps:
        - checkout
        - run:
            name: Integration Test
            command: mvn verify
        # Storing some results as artifacts to be viewable in CircleCI
        - store_artifacts:
            path:  target/site/jacoco
        - store_artifacts:
            path:  target/surefire-reports
  # Job to deploy to master
  merge:
      executor: doc
      steps:
        - checkout
        - run:
            name: Merge
            command: git checkout master ; git merge << pipeline.git.branch	 >>